# Generated by Django 5.1.3 on 2024-12-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa_deportiva', '0003_tenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenis',
            name='talla',
            field=models.IntegerField(choices=[('24', '24'), ('25', '25'), ('26', '26'), ('27', '27')]),
        ),
    ]
